In [2]:
import pandas as pd

In [4]:
# Data files to be combined 
files23 = ['data/JC-202310-citibike-tripdata.csv', 'data/JC-202311-citibike-tripdata.csv', 'data/JC-202312-citibike-tripdata.csv']

# Empty list to store each dataframe
df23_list = []

# Loop through each file in the list
for file in files23:
    # Read the file into a dataframe
    df23 = pd.read_csv(file)

    # Append the dataframe to the list
    df23_list.append(df23)

# Concatenate all dataframes in the list into one dataframe
df23 = pd.concat(df23_list)

# Show dataframe
df23

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,56269E94B2206375,classic_bike,2023-10-31 11:52:42,2023-10-31 12:03:33,McGinley Square,JC055,Marin Light Rail,JC013,40.725340,-74.067622,40.714584,-74.042817,member
1,2B2F6514026F5C68,classic_bike,2023-10-16 08:24:33,2023-10-16 08:35:28,Astor Place,JC077,Grove St PATH,JC115,40.719299,-74.071357,40.719410,-74.043090,member
2,3716C0E2166FE548,classic_bike,2023-10-21 11:46:26,2023-10-21 11:56:30,McGinley Square,JC055,Grove St PATH,JC115,40.725428,-74.067577,40.719410,-74.043090,member
3,E06BF0A228598DDF,classic_bike,2023-10-26 09:42:42,2023-10-26 09:51:28,Astor Place,JC077,Marin Light Rail,JC013,40.719267,-74.071328,40.714584,-74.042817,member
4,1EA3E3FFB17B6B16,classic_bike,2023-10-22 13:20:54,2023-10-22 15:00:09,McGinley Square,JC055,Grove St PATH,JC115,40.725340,-74.067622,40.719410,-74.043090,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58675,7E862701EE7A6A03,classic_bike,2023-12-20 17:55:41,2023-12-20 18:00:10,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748720,-74.040487,40.754530,-74.026580,casual
58676,DFAF91AB91BE25DB,classic_bike,2023-12-13 14:36:43,2023-12-13 14:42:31,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748767,-74.040470,40.754530,-74.026580,member
58677,AEE7B49E6EDFAE6F,classic_bike,2023-12-18 16:40:00,2023-12-18 16:45:45,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744291,-74.034404,40.754530,-74.026580,member
58678,A38E98956AD72EFB,classic_bike,2023-12-02 13:42:51,2023-12-02 13:50:42,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744398,-74.034501,40.754530,-74.026580,member
58679,F16E0B969D877368,classic_bike,2023-12-19 16:30:13,2023-12-19 16:36:54,6 St & Grand St,HB302,Clinton St & 7 St,HB303,40.744398,-74.034501,40.745420,-74.033320,member

In [5]:
# Save the dataframe to a CSV file
df23.to_csv('data/citibike23.csv', index=False)